variables:
  CONTAINER_TEST_IMAGE:  registry.gitlab.com/linux-be/overlay:$CI_COMMIT_SHA
  CONTAINER_RELEASE_IMAGE: registry.gitlab.com/linux-be/overlay:latest

build-image:
  stage: build
  tags:
    - docker-build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

verify-repo:
  image:
    name: chaoslab/repoman
    entrypoint: [""]
  stage: verify
  script:
    - repoman --mode scan -xq || exit 0

release-image:
  stage: release
  tags:
    - docker-build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master

stages:
  - build
  - verify
  - release
