verify-repo:
  image:
    name: aegypius/repoman
    entrypoint: [""]
  stage: verify
  script:
    - repoman --mode scan -xq || exit 0

verify-linux-be-changes:
  image:
    name: bitnami/minideb
  stage: verify
  script:
    - ./sanity.sh

stages:
  - verify
