Global:
  ManageImages: true
  BootMountPoint: /boot/efi
Components:
  ImageDir: /boot/efi/EFI/zfsbootmenu
  Versions: false
  Enabled: true
  syslinux:
    Config: /boot/syslinux/syslinux.cfg
    Enabled: false
EFI:
  ImageDir: /boot/efi/EFI/zfsbootmenu
  Versions: false
  Enabled: false
  Stub: /usr/lib/systemd/boot/efi/linuxx64.efi.stub
Kernel:
  CommandLine: ro quiet loglevel=0
